name: snorkel
version: '0.0.19' # just for humans, typically '1.2+git' or '1.3.2'
summary: logv analytics server and backend
description: |
  The logv analytics server is an all in one data management system. Comprised
  of snorkel (a nodejs based query explorer) and sybil (a go based
  instrumentation backend), the logv stack is meant for quick setup and and
  analysis of instrumentation.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  snorkel:
    # See 'snapcraft plugins'
    source: git://github.com/logv/snorkel
    # source: /home/okay/tonka/src/snorkel.sf
    source-subdir: snorkel
    plugin: nodejs

    build-packages:
      - libleveldb-dev
      - libsqlite3-dev
      - build-essential

    node-packages:
      - connect-sqlite3
      - leveldown
      - linvodb3

    snap:
      - bin/*
      - include/*
      - lib/*
      - -.git*
      - -lib/node_modules/snorkel/node_modules.bak
      - -lib/node_modules/snorkel/db
      - -lib/node_modules/snorkel/sessions.db


  sybil:
    plugin: go
    source: git://github.com/logv/sybil
    # source: /home/okay/tonka/src/sybil/

  snapglue:
    source: git://github.com/logv/snapcraft
    plugin: copy
    files:
      bin/snorkel_wrapper: bin/snorkel_wrapper
      bin/sybil_wrapper: bin/sybil_wrapper

apps:
  frontend:
    command: bin/snorkel_wrapper
    plugs:
      - network
      - network-bind
      - log-observe

  backend:
    command: bin/sybil_wrapper
