name: snorkel
version: '0.3.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: logv analytics server and backend
description: |
  The snorkel analytics server is an all in instrumentation system. Comprised
  of snorkel (a nodejs based query explorer) and sybil (a go based
  instrumentation backend), the snorkel stack is meant for quick setup and
  analysis of instrumentation.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  snorkel:
    # See 'snapcraft plugins'
    source: git://github.com/logv/snorkel
    # source: /home/okay/tonka/src/snorkel.sf
    source-subdir: snorkel
    plugin: nodejs

    build-packages:
      - libleveldb-dev
      - libsqlite3-dev
      - build-essential

    node-packages:
      - connect-sqlite3
      - leveldown
      - linvodb3

    snap:
      - -config/users.htpasswd
      - -config/users.rbac
      - bin/*
      - include/*
      - lib/*
      - -.git*
      - -lib/node_modules/snorkel/node_modules.bak
      - -lib/node_modules/snorkel/db
      - -lib/node_modules/snorkel/sessions.db


  sybil:
    plugin: go
    source: git://github.com/logv/sybil
    # source: /home/okay/tonka/src/sybil/
    go-importpath: github.com/logv/sybil
    go-buildtags:
      - luajit

    build-packages:
      - libluajit-5.1-dev

  snapglue:
    source: git://github.com/logv/snapcraft
    # source: .
    plugin: copy
    files:
      bin/add_user_wrapper: bin/add_user_wrapper
      bin/snorkel_wrapper: bin/snorkel_wrapper
      bin/sybil_wrapper: bin/sybil_wrapper

apps:
  frontend:
    command: bin/snorkel_wrapper
    plugs:
      - network
      - network-bind
      - log-observe

  add-user:
    command: bin/add_user_wrapper

  backend:
    command: bin/sybil_wrapper
